# Generated by Django 4.1.3 on 2022-11-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emplyee_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emplyee_regNo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
